# Generated by Django 5.0.1 on 2024-01-16 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('tag', models.CharField(choices=[('BUG', 'Bug'), ('FEATURE', 'Amélioration'), ('TASK', 'Tâche')], max_length=7)),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute')], max_length=6)),
                ('status', models.CharField(choices=[('TODO', 'A faire'), ('INPROGRESS', 'En cours'), ('FINISHED', 'Fini')], default='TODO', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issue_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issue_created_by', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_related', to='Project.project')),
            ],
        ),
    ]
