# Generated by Django 3.1.4 on 2024-01-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240115_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_be_contacted',
            field=models.CharField(choices=[('option1', 'Oui'), ('option2', 'Non')], default='Oui', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_data_be_shared',
            field=models.CharField(choices=[('option1', 'Oui'), ('option2', 'Non')], default='Oui', max_length=7),
        ),
    ]
