# Generated by Django 5.0.1 on 2024-01-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_be_contacted',
            field=models.CharField(choices=[('option1', 'Oui'), ('option2', 'Non')], default='Oui', max_length=7, verbose_name='Peut être contacté?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_data_be_shared',
            field=models.CharField(choices=[('option1', 'Oui'), ('option2', 'Non')], default='Oui', max_length=7, verbose_name='Peut-on partager les données?'),
        ),
    ]
