# Generated by Django 5.0.1 on 2024-01-21 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('issue', '0003_alter_issue_description'),
        ('users', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributor_comment', to='comment.comment'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributor_issue', to='issue.issue'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_be_contacted',
            field=models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='Oui', max_length=7, verbose_name='Peut être contacté?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_data_be_shared',
            field=models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='Oui', max_length=7, verbose_name='Peut-on partager les données?'),
        ),
    ]
